import time 
import random

class Questions:
    def __init__(self, question, options, answer):
        self.question = question
        self.options = options
        self.answer = answer

questions = {
    "easy": [
        Question("What is the capital of France?",
                 ["A) Paris", "B) London", "C) Berlin", "D) Madrid"],
                 "A"),
        Question("Which planet is known as the Red Planet?",
                 ["A) Earth", "B) Mars", "C) Jupiter", "D) Saturn"],
                 "B"),
        Question("Who painted the Mona Lisa?",
                 ["A) Vincent van Gogh", "B) Leonardo da Vinci", "C) Pablo Picasso", "D) Michelangelo"],
                 "B"),
        Question("What is the largest mammal in the world?",
                 ["A) Elephant", "B) Blue Whale", "C) Giraffe", "D) Lion"],
                 "B"),
        Question("Which gas do plants primarily use for photosynthesis?",
                 ["A) Oxygen", "B) Nitrogen", "C) Hydrogen", "D) Carbon Dioxide"],
                 "D"),
        Question("What is the capital of Japan",
                 ["A) Beijing", "B) Tokyo", "C) Seoul", "D) Bangkok"],
                 "B"),
        Question("Which famous scientist developed the theory of relativity?",
                 ["A) Isaac Newton", "B) Galileo", "C) Einstein", "D) Stephen Hawking"],
                 "C"),
        Question("Which ocean is the largest on Earth?",
                 ["A) Atlantic", "B) Indian", "C) Pacific", "D) Arctic"],
                 "C"),
        Question("What is the main function of the heart?",
                 ["A) Pump Blood", "B) Digestion", "C) Produce Hormones", "D) Filtering waste"],
                 "A"),
        Question("What is the process by which plants make their own food using sunlight?",
                 ["A) Respiration", "B) Transpiration", "C) Photosynthesis", "D) Combustion"],
                 "C"),
    ],
    "hard": [
        Question("In which year was the Python programming language first released?",
                 ["A) 1989", "B) 1991", "C) 2000", "D) 2005"],
                 "B"),
        Question("What is the smallest prime number?",
                 ["A) 0", "B) 1", "C)2", "D)3"],
                 "C"),
        Question("Which philosopher is known for his work Critique of Pure Reason?",
                 ["A) Paris", "B) London", "C) Berlin", "D) Madrid"],
                 "A"),
        Question("What is the largest species of shark?",
                 ["A) Earth", "B) Mars", "C) Jupiter", "D) Saturn"],
                 "B"),
        Question("In which year did the Berlin Wall fall, leading to the reunification of Germany?",
                 ["A) 1985", "B) 1989", "C) 1991", "D) 1995"],
                 "A"),
        Question("Which novel features the characters Winston Smith and Big Brother?",
                 ["A) Earth", "B) Mars", "C) Jupiter", "D) Saturn"],
                 "B"),
        Question("What is the rarest blood type among humans?",
                 ["A) Paris", "B) London", "C) Berlin", "D) Madrid"],
                 "A"),
        Question("Which artist painted The Persistence of Memory, featuring melting clocks?",
                 ["A) Earth", "B) Mars", "C) Jupiter", "D) Saturn"],
                 "B"),
        Question("What is the largest organ in the human body?",
                 ["A) Paris", "B) London", "C) Berlin", "D) Madrid"],
                 "A"),
        Question("Which particle is responsible for carrying the electromagnetic force?",
                 ["A) Earth", "B) Mars", "C) Jupiter", "D) Saturn"],
                 "B"),
    ]
}